/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.0.4 and the Signal Processing Toolbox 6.3.
 *
 * Generated on: 20-Feb-2007 12:45:31
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB704\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 9
const int bp_4k_48000_bl[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const real64_T bp_4k_48000_b[MWSPT_NSEC][3] = {
  {
  1.240780983352e-006,                 0,                 0 
  },
  {
                   1,  -0.9323999174998,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.944221102086,    1.000000000001 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.48009018957,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.866739488078,   0.9999999999991 
  },
  {
                   1,                 0,                 0 
  }
};
const int bp_4k_48000_al[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const real64_T bp_4k_48000_a[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.719151456744,   0.9911303232335 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.729925201271,   0.9912922673717 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.715843320582,   0.9962827713976 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.741684237502,   0.9964446600911 
  },
  {
                   1,                 0,                 0 
  }
};
