/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.0.4 and the Signal Processing Toolbox 6.3.
 *
 * Generated on: 20-Feb-2007 12:50:06
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB704\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 9
const int bp_4k_32000_bl[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const real64_T bp_4k_32000_b[MWSPT_NSEC][3] = {
  {
  1.557727862934e-006,                 0,                 0 
  },
  {
                   1, -0.05889419444987,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.879015468291,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.9143784524301,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.707346209925,   0.9999999999999 
  },
  {
                   1,                 0,                 0 
  }
};
const int bp_4k_32000_al[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const real64_T bp_4k_32000_a[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.393763966652,   0.9867406367536 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.41642220176,   0.9869501238575 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.382799673538,   0.9944463132202 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.437416461937,   0.9946562156666 
  },
  {
                   1,                 0,                 0 
  }
};
