/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.0.4 and the Signal Processing Toolbox 6.3.
 *
 * Generated on: 20-Feb-2007 12:48:16
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB704\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 9
const int bp_4k_44100_bl[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const real64_T bp_4k_44100_b[MWSPT_NSEC][3] = {
  {
  1.286228000225e-006,                 0,                 0 
  },
  {
                   1,   -0.777449756023,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.934272257186,   0.9999999999999 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.390893175439,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.842688442774,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int bp_4k_44100_al[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const real64_T bp_4k_44100_a[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.669653837785,   0.9903513630323 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.682283998073,   0.9905241026682 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.665252282229,   0.9959564894443 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.695579053616,   0.9961292130839 
  },
  {
                   1,                 0,                 0 
  }
};
