/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.0.4 and the Signal Processing Toolbox 6.3.
 *
 * Generated on: 20-Feb-2007 10:14:06
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB704\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 7
const int ccir468_3200_bl[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real64_T ccir468_3200_b[MWSPT_NSEC][3] = {
  {
                0.85,                 0,                 0 
  },
  {
                   0,                 0,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   0,                 1,              1.25 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,             -0.25,             -0.75 
  },
  {
                   1,                 0,                 0 
  }
};
const int ccir468_3200_al[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real64_T ccir468_3200_a[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.3018895519067, 0.001831175289608 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.3418104418624,   0.1605919523439 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  0.02389592443884,   0.2712458472197 
  },
  {
                   1,                 0,                 0 
  }
};
