/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.0.4 and the Signal Processing Toolbox 6.3.
 *
 * Generated on: 20-Feb-2007 10:00:08
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB704\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 7
const int bl[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real64_T b[MWSPT_NSEC][3] = {
  {
                0.57,                 0,                 0 
  },
  {
                   0,                 0,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   0,                 1,              1.28 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,             -0.28,             -0.72 
  },
  {
                   1,                 0,                 0 
  }
};
const int al[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real64_T a[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.4996051251967,  0.04498925718828 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.5959980328644,   0.1945178712489 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.3201613144549,   0.2786610420578 
  },
  {
                   1,                 0,                 0 
  }
};
