/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.0.4 and the Signal Processing Toolbox 6.3.
 *
 * Generated on: 06-Mar-2007 13:17:08
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB704\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 7
const int ccir468_48000_bl[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real64_T ccir468_48000_b[MWSPT_NSEC][3] = {
  {
                0.48,                 0,                 0 
  },
  {
                   0,                 0,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   0,                 1,               1.3 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,              -0.3,              -0.7 
  },
  {
                   1,                 0,                 0 
  }
};
const int ccir468_48000_al[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real64_T ccir468_48000_a[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.5487086419646,  0.05893223939424 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.6559555694605,   0.2055424994159 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.4057275318695,   0.2832708097676 
  },
  {
                   1,                 0,                 0 
  }
};
