/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.0.4 and the Signal Processing Toolbox 6.3.
 *
 * Generated on: 06-Mar-2007 13:22:28
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 6
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB704\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 13
const int lp_48000_bl[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T lp_48000_b[MWSPT_NSEC][3] = {
  {
     0.1275989262439,                 0,                 0 
  },
  {
                   1,    1.995675171563,    1.000000000006 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.965358497856,   0.9999999999984 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.921873305357,    1.000000000002 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.882693109174,   0.9999999999987 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.855976944139,    1.000000000001 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.842969114423,   0.9999999999998 
  },
  {
                   1,                 0,                 0 
  }
};
const int lp_48000_al[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T lp_48000_a[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   0.2109884926187,  0.09547522466767 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   0.9190570840754,   0.5005607119249 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.367593671118,   0.7581128988096 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.579771612679,   0.8818361401189 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.682557369684,   0.9451969883445 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.735231834136,   0.9838826125212 
  },
  {
                   1,                 0,                 0 
  }
};
