/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.0.4 and the Signal Processing Toolbox 6.3.
 *
 * Generated on: 20-Feb-2007 10:18:00
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 6
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB704\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 13
const int dr_lp_44100_bl[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T dr_lp_44100_b[MWSPT_NSEC][3] = {
  {
     0.3264435464712,                 0,                 0 
  },
  {
                   1,    1.998757475239,   0.9999999999997 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.989993373019,   0.9999999999998 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.977254757142,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,     1.96560453861,   0.9999999999995 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.957564737001,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.953621726441,   0.9999999999999 
  },
  {
                   1,                 0,                 0 
  }
};
const int dr_lp_44100_al[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T dr_lp_44100_a[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   0.8321624415298,   0.2336661152884 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.443215547293,   0.6571177836971 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.723522054025,   0.8517567075263 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.836701633172,   0.9310881176054 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,      1.8886071568,   0.9687780372787 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.915942311091,   0.9909283814552 
  },
  {
                   1,                 0,                 0 
  }
};
