/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.0.4 and the Signal Processing Toolbox 6.3.
 *
 * Generated on: 20-Feb-2007 12:39:45
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB704\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 9
const int no_4k_32000_bl[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const real64_T no_4k_32000_b[MWSPT_NSEC][3] = {
  {
     0.8721885623254,                 0,                 0 
  },
  {
                   1,   -1.414213562373,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.414213562373,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.414213562373,                 1 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.414213562373,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int no_4k_32000_al[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const real64_T no_4k_32000_a[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.366682377855,   0.9327807542182 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.366682377855,   0.9327807542182 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.366682377855,   0.9327807542182 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.366682377855,   0.9327807542182 
  },
  {
                   1,                 0,                 0 
  }
};
